### ISSUE TITLE
buildHeaderParam fails if data string contains double width unicode char

### ISSUE THREAD

**Issue by andrewtamura** [nodemailer/libmime#4]
See PR https://github.com/andris9/libmime/pull/3 for a test case.

**Comment by andris9** [comment]
Yes, I checked and it definitely is a bug. This is caused by encodeURIComponent that encodes characters not as a full string but one character at a time. I'll try to think something out.

**Comment by andrewtamura** [comment]
thanks!

**Comment by andris9** [comment]
I think this got fixed a long time ago. Closing
