### ISSUE TITLE
Issue with parenthesis in an attachment filename

### ISSUE THREAD

**Issue by surajwy** [nodemailer/libmime#5]
Hi Andris,

If an attachment filename is having parenthesis in it, Ex:
- a(a.txt
- a)a.txt

And if you upload it to a mailbox (or send it to the recipient), then, if you try to get the structure (IMAP command: BODY or ENVELOPE BODYSTRUCTURE) of it, then these attachments will not be visible. All those clients who maintain their email metadata using envelope will go for a toss. Even Gmail is going bonkers. This probably happens because an email mime structure/envelope is expressed and parsed based on opening and closing of a parenthesis.

The correct way here is to keep such filenames in quotes. So, will it be safe if I update the regex [here](https://github.com/nodemailer/libmime/blob/master/lib/libmime.js#L348) with **[\s'"\\;\\/=\\(\\)]**  ?

Thanks, 
Suraj

**Comment by andris9** [comment]
Could you make a pull request for it and also add a unit test for buildHeaderValue that uses such attachment name?

**Comment by surajwy** [comment]
Sure, I'll do it now.

**Comment by surajwy** [comment]
Hi,

I've come across few more characters because of which we should put the filename in quotes.
Refer: https://www.w3.org/Protocols/rfc1341/4_Content-Type.html

Here is the grammar for that:

```
Content-Type := type "/" subtype *[";" parameter] 

type :=          "application"     / "audio" 
          / "image"           / "message" 
          / "multipart"  / "text" 
          / "video"           / x-token 

x-token := <The two characters "X-" followed, with no 
           intervening white space, by any token> 

subtype := token 

parameter := attribute "=" value 

attribute := token 

value := token / quoted-string 

token := 1*<any CHAR except SPACE, CTLs, or tspecials> 

tspecials :=  "(" / ")" / "<" / ">" / "@"  ; Must be in 
           /  "," / ";" / ":" / "\" / <">  ; quoted-string, 
           /  "/" / "[" / "]" / "?" / "."  ; to use within 
           /  "="                        ; parameter values
```

Should I go ahead and make necessary changes and send you a PR for this? IMHO, we should do this. Please share your opinion on this.

Thanks,
Suraj

**Comment by andris9** [comment]
Yeah, would be great if you could create a PR for this. My original implementation was quite naive about that, it would be much better to actually follow the spec
